### ISSUE TITLE
Add preconfigured ConsulService 

### ISSUE THREAD

**Issue by hendrik-rebuy** [rebuy-de/rebuy-silo-archetype#29]
ConsulService is not configured at the moment but is a needed bean

**Comment by etwillbefine** [comment]
this can be replaced in favor of this [merged PR](https://github.com/rebuy-de/rebuy-silo-archetype/pull/30)?

**Comment by hendrik-rebuy** [comment]
what do you mean replaced that PR closes this issue.

**Comment by hendrik-rebuy** [comment]
closed by https://github.com/rebuy-de/rebuy-silo-archetype/pull/30
