### ISSUE TITLE
v4.1.0 missing mocked consulService in test conf

### ISSUE THREAD

**Issue by cbertilsson** [rebuy-de/rebuy-silo-archetype#52]
I created the silo grading-connector-blancco using archetype v 4.1.0 today (built 10/06/2016, http://maven.dc1.rebuy/repository/com/rebuy/archetypes/rebuy-silo-archetype/4.1.0/), and this fix was not included (commited on 20/05/2016): 

https://github.com/rebuy-de/rebuy-silo-archetype/commit/e7508d6bac2b56a6faf8b8e092d69b593baf0464

A new version needs to be released?

@rebuy-de/prp-rebuy-silo-archetype

**Comment by das-vinculum** [comment]
@cbertilsson Yes you need to create a new release,, can you create one?

**Comment by cbertilsson** [comment]
I was in Italy last week, so here comes a late reply @das-vinculum.

There has been releases made, this documentation update from Björn clarifies how to use the latest releases: https://github.com/rebuy-de/documentation/commit/3250a18760123413a86a16329f9a5fd44af710c0

Closing this issue.
